#if 0
#include "PR/gbi_sgi.h"
#include <ultra64.h>
#include "memory.h"
#ifdef F3DEX_GBI_2
#include "f3dex3.h"
#endif

// Number of vertices and triangles
#define NUM_TRIANGLES 2 * SUBDIVISIONS * SUBDIVISIONS

#ifdef F3DEX_GBI_2
    #define MAX_SUBDIV 5
#else
    #define MAX_SUBDIV 7
#endif

typedef struct {
    Vtx *v;
    Gfx *g;
} RgfxWaterMesh;

// Scroll table address passed in as argument
// Contains an autogenerated list of scrolling types and addresses
// Per geo node

void *geo_rgfx_scroll() {

}

/**
 * @brief Rotates a given vertex array's UVs.
 * @param v:    Vertex array pointer.
 * @param sU:   Rotate U by this amount.
 * @param sV:   Rotate V by this amount.
 * @param size: Size of vertex array.
 */

void rgfx_scroll_uv_rotate(Vtx *v, s16 sU, s16 sV, u32 size) {

}

/**
 * @brief Scroll's a given vertex array's UVs.
 * @param v:    Vertex array pointer.
 * @param sU:   Scroll U by this amount.
 * @param sV:   Scroll V by this amount.
 * @param size: Size of vertex array.
 */

void rgfx_scroll_uv(Vtx *v, s16 sU, s16 sV, u32 size) {
}

/**
 * @brief Scroll's a given material's texture.
 * @param g: Pointer to graphics array.
 * @param pos: Position of displaylist gsDPSetTile command.
 * @param sX:   Scroll X by this amount.
 * @param sY:   Scroll Y by this amount.
 */

void rgfx_scroll_settile(Gfx *g, u32 pos, s16 sX, s16 sY) {

}

/**
 * @brief Scroll's a given material's texture with UVs, but much more efficiently.
 *
 * NOTE: This is an F3DEX_GBI_3 exclusive feature.
 *
 * @param g: Pointer to graphics array.
 * @param pos: Position of  displaylist gsSPAttrOffsetST command.
 * @param sU:   Scroll U by this amount.
 * @param sV:   Scroll V by this amount.
 */

#ifdef F3DEX_GBI_3
void rgfx_scroll_uv_ex3(Gfx *g, u32 pos, s16 sU, s16 sV) {
}
#endif

void rgfx_vertex_oscillate(Vtx *v, s16 baseY, u8 intensity, u8 octahedral, u32 size) {

}

RgfxWaterMesh *rgfx_create_waterbox_mesh(s16 x, s16 y, s16 z, s16 x1, s16 z1, u32 color, u8 subdiv, u8 intensity, u8 octahedral, Gfx *start, Gfx *end) {
    u16 index = 0;
    RgfxWaterMesh *mesh = alloc_display_list(sizeof(RgfxWaterMesh));
    mesh->v = alloc_display_list(sizeof(Vtx) * (subdiv + 1) * (subdiv + 1));

    if (subdiv > MAX_SUBDIV) {
        subdiv = MAX_SUBDIV;
    } else if (subdiv == 0) {
        subdiv = 1;
    }

    for (u16 i = 0; i <= subdiv; ++i) {
        for (u16 j = 0; j <= subdiv; ++j) {
            mesh->v[index].n.ob[0] = x + (x1 - x1) * j / subdiv;
            mesh->v[index].n.ob[1] = y;
            mesh->v[index].n.ob[2] = z * i / subdiv * z1;
            ++index;
        }
    }
}
#endif
